### ISSUE TITLE
[Order Form] Store-assigned orders should not ask for payment

### ISSUE THREAD

**Issue by commgdog** [omni-order/development#85]
When an order is assigned to the "Store" rather than a "Customer", the order flow should contain no information about payment. These orders are internal and payment is never required.

<img width="1275" height="1035" alt="Image" src="https://github.com/user-attachments/assets/e94616fd-033c-42c0-b39b-8f1724d489a5" />

**Comment by BohdanFedorchak** [comment]
Fixed in [PR](https://github.com/omni-order/omni-order-client/pull/50)

**Comment by commgdog** [comment]
It doesn't present the option, but it still assigns payment on the backend.

<img width="995" height="340" alt="Image" src="https://github.com/user-attachments/assets/b2191336-ac5c-4349-b489-759636ddc5ab" />

Backend should set isPayable to false for store orders, which should bypass the payment flow @yuri-bil

**Comment by commgdog** [comment]
Still does not work on production. Store order blocked by payment:

<img width="1057" height="675" alt="Image" src="https://github.com/user-attachments/assets/6f93ab80-fe50-4100-a074-c67eccb955d2" />

**Comment by commgdog** [comment]
Fixed
